Incorporate changes as per our us-ds discussion
tradej/kie-docs pull request #1
Opened 2017-08-03 13:45 UTC by m-czernek

Adding back the relative imagesdir paths as we now handle that in our pre-processing scripts. Additionally, I corrected the `optaplanner-wb-es-docs/src/main/asciidoc/brms/topics` symlink and `optaplanner-wb-es-docs/src/main/asciidoc/community/index.adoc` include.

WDYT?

2017-08-03 14:31 UTC, tradej requested changes

2017-08-03 14:31 UTC, tradej commented on docs/optaplanner-wb-es-docs/src/main/asciidoc/community/index.adoc
> -include::../topics/main.adoc[]
Please remove the `community` directory, it is completely unnecessary.

2017-08-04 07:53 UTC, m-czernek commented on docs/optaplanner-wb-es-docs/src/main/asciidoc/community/index.adoc
> -include::../topics/main.adoc[]
Removed.

2017-08-04 12:37 UTC, tradej approved these changes

2017-08-04 12:38 UTC, merged